### ISSUE TITLE
関連があるものはまとめるほうがみやすい

### ISSUE THREAD

**Issue by c0b2116968** [c0b2113943/ProjExD#10]
https://github.com/c0b2113943/ProjExD/blob/0babd874de75daaa0cc3aa186a7b4433d3720fbb/ex03/maze.py#L4
cx,cy = 150,150のような感じ

**Comment by 43zaki** [comment]
了解です

**Comment by c0b2113943** [comment]
まとめました。　次回からは気おつけます。
