### ISSUE TITLE
もっと見やすく

### ISSUE THREAD

**Issue by 43zaki** [c0b2113943/ProjExD#12]
https://github.com/c0b2113943/ProjExD/blob/0babd874de75daaa0cc3aa186a7b4433d3720fbb/ex03/maze.py#L33
33行目から48行目までは
if key == "Up" and maze_source[my-1][mx] != 1:
        my -= 1
    elif key == "Down" and maze_source[my+1][mx] != 1:
        my += 1
    elif key == "Left" and maze_source[my][mx-1] != 1:
        mx -= 1
    elif key == "Right" and maze_source[my][mx+1] != 1:
        mx += 1
        
    cx = mx*100 + 50
    cy = my*100 + 50
    canvas.coords(bird, cx, cy)

こんな感じで書けるし分かりやすいと思う

**Comment by c0b2113943** [comment]
次回からは気を付けます
