### ISSUE TITLE
モジュール

### ISSUE THREAD

**Issue by c0b21177** [c0b2113943/ProjExD#16]
https://github.com/c0b2113943/ProjExD/blob/f9ff3eeacc06ef0dc30915e80a48dd014ef39a87/ex04/dodge_bomb.py#L3
インポートしたのに使っていないです

**Comment by c0b2113943** [comment]
勝手にはいいてしまったようです。消去します

**Comment by c0b2113943** [comment]
aのほうは＃つけ忘れて送ってしまい戻しています。消しましたのほうが直した方です。
